
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

# buttons functionality
def on_radio_button_click(event):
    global cliked
    cliked = event

def submit():

    if cliked == 'Doctors' :
        try :
            doctorinfo = db.reference(f'Doctors/{email_entry.get()}').get()
            if  doctorinfo['password'] == pass_entry.get():
                messagebox.showinfo("Success", f'Welcome : DR / {doctorinfo["name"]}')
            else :
                messagebox.showerror("Error", 'invalid password')

        except:
            messagebox.showerror("Error", 'invalid username')
    elif cliked == 'Students' :
        if  email_entry.get() == 'Affairs' and pass_entry.get() == '123' :
            messagebox.showinfo("Success", 'Welcome')
        else :
            messagebox.showerror("Error", 'invalid username or password')
     elif cliked == 'Courses':
            if email_entry.get() == 'Affairs' and pass_entry.get() == '123':
                messagebox.showinfo("Success", 'Welcome')
            else:
                messagebox.showerror("Error", 'invalid username or password')
    import Affairs_Doctor

window = Tk()
window.title('Affairs Management System')
window.geometry("1280x700+100+50")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 700,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file='assets/frame0/image_1.png')
image_1 = canvas.create_image(
    640.0,
    350.0,
    image=image_image_1
)

bg_image = PhotoImage(
    file='assets/frame0/image_2.png')
image_2 = canvas.create_image(
    628.0,
    350.0,
    image=bg_image
)

courses_image = PhotoImage(
    file='assets/frame0/button_1.png')
courses_button = Button(
    image=courses_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Doctors"),
    relief="flat"
)
courses_button.place(
    x=700.0,
    y=464.0,
    width=413.0,
    height=64.0
)

canvas.create_text(
    120.0,
    190.0,
    anchor="nw",
    text="Hi!\nWelcome back to the\nAffairs Management System",
    fill="#FFFFFF",
    font=('Perpetua', 33, 'bold')
)

canvas.create_text(
    126.0,
    367.0,
    anchor="nw",
    text="Go on and click any button you want to edit it's details",
    fill="#FFFFFF",
    font=("Perpetua", 19)
)

student_image = PhotoImage(
    file='assets/frame0/button_2.png')
student_button = Button(
    image=student_image,
    borderwidth=0,
    highlightthickness=0,
    command=Student_click,
    relief="flat"
)
student_button.place(
    x=685.0,
    y=319.0,
    width=432.0,
    height=63.0
)

doc_image = PhotoImage(
    file='assets/frame0/button_3.png')
doc_button = Button(
    image=doc_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Courses"),
    relief="flat"
)
doc_button.place(
    x=686.0,
    y=165.0,
    width=432.0,
    height=63.0
)
window.resizable(False, False)
window.mainloop()
